---
title: "The inside curve: geometry and pollination ecology of curved flowers"
author:
date: "2019-02-14"
output: 
  html_document: 
    fig_caption: yes
bibliography: curvature_review.bib
csl: cell.csl
link-citations: true
---

<br>
<br>

```{r include=FALSE} 
knitr::opts_chunk$set(echo=FALSE, warning=FALSE, message=FALSE)
```




<br>

 




You can also embed plots, for example:

```{r curve_example, results='hide', fig.cap="Figure 1. Very cool figure that I done made."}


library(here)
library(Momit)
library(Momocs)

centro<-from_tps("centropogon_dorsal_appended.tps") 

#inspect 
str(centro)
centro$LM[1]
centro$LM[2]

centro_imp<-fgProcrustes(centro$LM)

#for species #2
centro_coo<-centro_imp$shp2 #isolates coordinates as a matrix
coo_plot(centro_coo)

centro_curv <- npoly(centro_coo, degree=4)
centro_curv

centro_shape<-npoly_i(centro_curv)
coo_draw(centro_shape)
lines(centro_shape, col='red')
```

<br>

```{r tables_lit_review}
table_1<-read.csv('Table_1_review_lit_curvature.csv', header=TRUE)
knitr::kable(table_1, caption = 'Table 1. Summary of literature reviewed for the role of curvature in plant-pollinator systems.')

table_2<-read.csv('Table_2_epimedium_flower_stages.csv', header=TRUE)
knitr::kable(table_2, caption = 'Table 2. Description of flower stages for Epimedium.')

```

#### References

