---
title: "Plant-pollinator specialization: Origin and measurement of curvature"
author:
date: ""
output:
   # word_document:
   #   fig_caption: yes
   #   reference_docx: curvature_review_reference.docx
  html_document:
  number_sections: no
  theme: flatly
  # pdf_document:
  # latex_engine: xelatex
bibliography: curvature_review.bib
csl: cell.csl
link-citations: true #'yes' for html, 'true' for pdfs
linkcolor: blue
urlcolor: blue
citecolor: blue
---

#### Abstract

The curvature of flowers and pollinators (e.g. hummingbird bills) along the lateral plane is a widespread, convergent trait with important ecological and evolutionary implications. This review summarizes and discusses why pollination ecologists are concerned with flower-pollinator curvature and what we have learned from its study. We then review the methods historically used to measure curvature and suggest a clarification of its definition by referring to the differential geometry literature. We demonstrate the applicability of the revised definition as a field-portable methodology. Intuitively, curvature is the degree to which a line is not straight. In plane geometry, curvature is defined as the rate at which the unit derivative changes direction with respect to arc length. To apply this definition we suggest a protocol wherein a line is regressed against landmarks placed on a lateral image of an organism, then computing curvature at many points along the fitted line and taking the sum. The utility of this metric was tested by studying the development of nectar spur curvature in _Epimedium_ (Berberidaceae). We found _Epimedium koreanum_ to have an order of magnitude greater curvature than the closely related _E. grandiflorum_ and _E. violaceum_. The suite of functions used to quantify floral curvature in this study are available as an open-source R package ‘kyokusen’.  The major advantages of this method are 1) precision of measurement is increased without introducing expensive field equipment or computing power, 2) precision of terminology within pollination ecology is improved by adopting from the existing mathematical tools for studying line-curves, and 3)  the opportunity is opened for investigating the genetic basis of (lateral plane) curvature measured at the cellular scale (not sure if this is worth commenting on.. cut if manuscript is too long?)

#### 1. The ecology of flower-pollinator curvature

> “We are beginning to understand why some hummingbird bills are long, whereas others are short, and why some hummingbird flowers are wide, whereas others are narrow. Now, why are bills of some hummingbirds and the tubes of the flowers they visit curved?” – @temeles_1996.

<br><br>

At the center of plant-pollinator diversification is a remarkable variety of floral form.  The notion that plant communities are under selection to reduce interspecific mating ['floral isolation', @grant_1949], points to the importance of floral diversity in initiating and reinforcing reproductive isolation [@armbruster_2009]. For example, in the rapid radiation of Andean _Centropogon_ (Campanulaceae), competition for pollination led to the divergence of floral traits associated with bat and hummingbird pollination [@lagomarsino_2019]. Meanwhile, in South African _Lapeirousia_ (Iridaceae), geographic variation in floral tube length has initiated reproductive isolation between morphs with short and long flower tubes, despite sharing the same fly pollinator [@minnaar_2019]. ADD IN EXAMPLE OF POLLINATOR DIVERSIFICATION. Thus, floral morphology is a key phenotypic feature associated with the diversification of plants and pollinators [@kay_2009; @ollerton_2017]. 

Flower-pollinator curvature as viewed from the side (lateral plane), has been a trait of special interest since the post-Darwin era of pollination ecology. In making pollinator observations of the Cape flora, Scott-Elliott [-@scott-elliot_1890] noticed that the flowers of _Leonotis ocymifolia_ (Lamiaceae) visited by _Nectarinia_ sunbirds were "curved with the same curvature as that of the bird's beak." (p. 272). Robertson [-@robertson_1889] insightfully notes that the curved nectar spurs of _Viola_ spp. (Violaceae) "serves to limit the insect visits much more than the mere length of the spur." (p. 172). From these early observations curvature has been synonymous with specialization; we expect curvature to limit the range of functional taxa in a plant-pollinator mutualism and strengthen interactions between the existing participants. And these expectations have largely been supported: Stiles [-@stiles_1975] first posited that neotropical _Heliconia_ partition hummingbird visitation by flower-bill curvature, and that specialization by curve-billed hummingbirds allow co-existence within the species-rich _Heliconia_ clade.  Subsequent research supports this hypothesis [@maglianesi_2014]:  along the slopes of the Central Cordillera (Costa Rica), the degree of flower-hummingbird bill curvature is proportional to plant-pollinator interaction strength [@dehling_2014] and extent of specialization (_d'_, [@bluthgen_2006]. More recently the scope of plant-pollinator research has expanded to address the biogeography of curvature. As predicted by Stiles [-@stiles_2004], Maglianesi [-@maglianesi_2015] and Sonne [-@sonne_2019] find curvature to be most prevalent in the lowland environments of the neotropics. Explanations for this pattern range from heightened competition at lower elevations to environmental filtering in the Andean highlands [@stiles_2004; @graham_2009]. Because the neotropical subfamily Phaethornithinae comprises the majority of hummingbird species with curved bills, we might expect plant-hummingbird curvature to have a predictable global distribution. In the case of honeycreepers and honeyeaters and sunbirds ???

Pollinator specialization has major effects on macroevolutionary and biogeographic patterns [@kay_2009; @armbruster_2009; @vamosi_2018], and curvature is a component, but widespread feature of specialist systems. Therefore,  to synthesize our knowledge of curved plant-pollinator systems, curvature is a concept that needs an exact definition and method of measurement. In the following section we summarize the approaches to measuring curvature within the field of bird pollination, identify strengths and shortcomings, and offer a solution with the aim of improving the precision with which curvature is measured within the field of pollination ecology. Although this review is motivated by the problem of measuring curvature in plant-hummingbird systems, the solution is general to any biological form modelled as a line curve: this case is hopefully made in the demonstration to follow. 

#### 2. Summary of the literature 

We searched the scientific literature for studies focusing on or considering floral curvature - a common measurement used in pollination ecology as a proxy for specialization. We make the distinction between measuring curvature in the lateral plane versus measuring curvature of surfaces (e.g. of petals). The methods for handling surface (Gaussian) curvature are relatively developed and well-defined [@nath_2003; @coen_2016]. The literature was sourced by querying Google Scholar for the terms "corolla curvature", "flower curvature", and "hummingbird curvature".  Results are summarized in Table 1. 25 studies of hummingbird-plant systems were found using some form of curvature metric (Table 1).  An additional 10 studies of other plant, insect, and passerine bird systems were found (Table S1). There were numerous studies of plant-pollinator shape that did not address curvature - these were omitted. 


WHERE DO THESE METHODS COME FROM? DO THEY CITE A MATHEMATICAL SOURCE? 
The discussion of lateral curvature in plant-hummingbird interactions begins with Hainsworth [-@hainsworth_1973] and is first empirically studied by Stiles [-@stiles_1975], though methods for measuring curvature of bird bills outside of a pollination context can be found much earlier [@baldwin_1931]. We identified six common approaches to measuring curvature. First, there are qualitative descriptions, e.g. "very curved", "less curved", but these are generally out of use. Second, the _arc:chord_ method wherein curvature is a ratio of two lines: a straight line (chord) from tip to base (of the flower or bill) and a line that traverses a path along the arc of the flower/bill ([Figure 1](Figures/Figure_1.jpg)). Third, the _mandibular index_ method which defines curvature as a ratio of two lines: a straight line from base to tip and a perpendicular line that measures the width of the flower/bill. This method is another form of the _arc:chord_ method because for a given chord length, the length of the perpendicular line will be proportional to the arc length.  Fourth, the _angle of deflection_ method which considers curvature as the angle between the base of the flower/bill and its tip. This is another form of the _inverse radius_ method which approximates the entire length of the flower/bill as a segment of a circle. These methods are interchangeable because the radius of a circle can be calculated from the length and angle of a line that passes through it [@bell_1956; @temeles_2009], see: [Figure S1](Figures/Figure_S1.jpg).  Sixth, geometric morphometrics, which quantifies shape as a configuration of homologous points (landmarks) existing on a coordinate plane ([Figure 2](Figures/Figure_2.jpg)). 

The strength of methods 2 and 3 are their portability and accessibility. These measurements can be taken in the field, or soon after from photographs. The methods are intuitive and in the simplest case, require only a ruler, string, and protractor. However, even if the measurements are made using imaging software these methods have some shortcomings [discussed in @berns_2010], principally that there are many shapes that could produce the same curvature value. For the _inverse radius_ method, a curve is approximated with the segment of a circle. This method is insufficient for any flower and bill shapes that deviate from having constant curvature (_e.g._ nectar spurs of _Delphinium_ ). Similarly, the _angle of deflection_ is not sensitive to local features along the length of the flower/bill - only the start and end points are considered in the calculation.  


An additional problem encountered with these methods is that the terminology surrounding them is inconsistent between authors. This likely stems from not citing the mathematical literature from which the methods were borrowed. For example, the _arc:chord_ method is also called the _maxillary index_, while the _angle of deflection_ method is sometimes refered to as the _angle of declension_ method. In the application of the _mandibular index_ one study adjusted for bill length while a subsequent study did not (Table 1). Most studies define their own terms for measuring curvature without reference to previous studies that have done the same, the result is a lexicon with many inconsistencies. 


Starting in 2010, geometric morphometrics (GM) emerges in the pollination literature. GM has since steadily gained in popularity in this field due to its statistical rigour, reproducibility, and the intuitive visual results presented as transformations of shape (_e.g._ illustrations of geographic variation in flower shape @gomez_2009). We briefly outline the reasoning of a GM protocol to introduce relevant concepts, but recommend the authoritative introduction to the topic written by Webster and Sheets [-@webster_2010]. A GM protocol for a 2-D object begins by placing the specimens on an _xy_ grid and assigning landmarks to locations on the specimen that are topologically or biologically homologous - a landmark is defined so that its location can be reproduced within and between samples. The set of landmarks representing the shape of an organism is a 'landmark configuration'.  In a comparative study, the samples must first be optimally aligned and their shape information isolated from their orientation, location, and size. This is done using a least-squares type protocol, most commonly the Generalized Procrustes Analysis (GPA). GPA-adjusted landmark configurations hereafter exist in a multidimensional shape space defined by the number of landmarks and spatial dimensions implemented. Each landmark configuration contains unique information about the specimen's shape, and as such, occupies a unique position in the corresponding shape space.  These configurations are then "projected" onto a simpler Euclidian space, similar to the reduction of a spherical Earth onto a two-dimensional map [@webster_2010]. From here, familiar statistical procedures (_e.g._ PCA) can be performed to quantify variation in landmark configurations (shape) between samples. 

This is giant leap forward for morphological studies because GM is a complete protocol for measuring, quantifying, and comparing shapes with high precision, as well as the covariation of these shapes with ecological variables of interest. The limitation of GM in quantifying curvature is that this method is concerned with analyzing configurations of landmarks, _i.e._ the entirety of a shape summarized as a set of _xy_ coordinates.  Once the specimen has been reduced to a landmark configuration, it exists as a point in shape space. Parsing segments of landmark configurations for separate analyses (_e.g._ for curvature) is not currently part of the geometric morphometrics toolkit. Therefore, studies that have used this technique to analyse biological forms are able to compare shapes in their entirety, but are ultimately limited to making descriptive statements about how segments of shapes appear to have different curvatures [_e.g._ @berns_2013, pp. 251]. 
