library(tidyverse)
library(here)


# ------------------------
# import alt curv metrics
alt_metrics <- 
  read.csv(file = here("data/alternative_metrics_rawdata.csv")) %>% 
  as_tibble() %>% 
  mutate(theta = 360 - theta)


# import total curvature data
curv_data <- 
  read_rds(here('data/RDS_files/spline_curvature_tbl_dorsal.rds')) 

# import pracma circles
pracma_circles <- read.csv(file=here('data/circles_fitby_pracma.csv'))

#create vars
totalK <- curv_data$total_K
angle_of_deflection <- alt_metrics$theta
arc_chord_ratio <- curv_data$perimeter / alt_metrics$chord
chord_versine_ratio <- alt_metrics$chord / alt_metrics$depth
# radius <- ((alt_metrics$chord / 2) / sin(angle_of_deflection*(pi/180))) #sin function operates on radians
radius <- pracma_circles[,2]


# -------------------------
# plot pairwise comparisons

#colours from http://www.cookbook-r.com/Graphs/Colors_(ggplot2)/ 
colour_ids <-
  c(replicate(30, "#E69F00"), #31 E. koreanum samples
    replicate(27, "#56B4E9")) #27 E. violaceum samples


#pairwise plots
library(GGally)

all_metrics <-
  tibble(colour_ids,
         totalK, 
         angle_of_deflection, 
         arc_chord_ratio, 
         chord_versine_ratio, 
         1/radius)

#store plot
pairwise_plot <- 
  ggpairs(
    all_metrics,
    columns = 2:6,
    mapping = aes(colour = colour_ids, alpha=0.35),
    columnLabels = 
      c("total curvature",
        "angle of deflection",
        "arc:chord ratio",
        "mandibular index",
        "inverse radius"),
    lower = list(continuous = wrap('smooth', alpha = 0.5, size = 3.5)),
    diag  = list(continuous = 'densityDiag', alpha = 0.3),
    upper = list(continuous = 'blank'))
    

#show plot
pairwise_plot + theme_classic() 
 



# ----------------------------------
# run stats on pairwise comparisons

library(Hmisc)

# pairwise comparisons of metrics for E. koreanum
pairK <- Hmisc::rcorr(as.matrix(all_metrics)[1:30, 2:6], type="pearson") 


# write.csv(data.frame(pairK$r), file=here('data/pairwiseK_r.csv'))
# write.csv(data.frame(pairK$P), file=here('data/pairwiseK_p.csv'))


# pairwise comparisons of metrics for E. violaceum
pairV <- Hmisc::rcorr(as.matrix(all_metrics)[31:57, 2:6], type="pearson")

# write.csv(data.frame(pairV$r), file=here('data/pairwiseV_r.csv'))
# write.csv(data.frame(pairV$P), file=here('data/pairwiseV_p.csv'))

# ----------------------
# inspect outliers

plot(1/radius, 
     totalK, 
     text(x=1/radius, 
          totalK, 
          labels=curv_data$name))

# koreanum outliers:
# 1_6_2(4), 1_8_3(10),  2_3_2(13), 2_5_1(16),
# 2_9_2(21), 2_9_3(22), 2_10_1(23)

# violaceum outliers:
# 2_3_5(44), 2_3_3(42)

# this data generated by pracma::circlefit() and pasted into this .csv
# lower RMS error is a better circle fit
rms_error <- 
  read.csv(file=here('data/circle_rms_error_pracma.csv')) 
  
# root of squared residuals between total_curvature and 1/R
res <- sqrt(residuals(lm(totalK~ 1/radius))^2)

# plot 
plot(rms_error$rms_error, 
     res,
     text(x=rms_error$rms_error, 
          y=res, 
          labels=curv_data$name))

summary(lm(rms_error$rms_error ~ res))
 